# Generated by Django 2.2.6 on 2019-10-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('src', models.CharField(max_length=20)),
                ('dest', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('available', models.PositiveIntegerField()),
                ('curr_lat', models.CharField(max_length=10)),
                ('curr_lon', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
