# Generated by Django 2.2.6 on 2019-10-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='available',
        ),
        migrations.AddField(
            model_name='bus',
            name='occupied',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.IntegerField(),
        ),
    ]
