# Generated by Django 2.2.6 on 2019-11-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbus', '0002_auto_20191031_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=10)),
                ('lon', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='avg_speed',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
