# Generated by Django 2.2.6 on 2019-11-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbus', '0003_auto_20191106_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='id',
        ),
        migrations.AlterField(
            model_name='bus',
            name='number',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
