# Generated by Django 2.2.6 on 2019-11-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbus', '0005_auto_20191106_0020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusStop',
            new_name='Stops',
        ),
    ]
