# Generated by Django 2.2.6 on 2019-11-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbus', '0006_auto_20191106_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stops',
            name='name',
        ),
        migrations.AlterField(
            model_name='stops',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
