# Generated by Django 2.2.6 on 2019-11-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbus', '0008_auto_20191106_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
